WallabyStuff/Marumaru

.swiftlint.yml
Marumaru.xcodeproj/project.pbxproj
Marumaru/AppDelegate.swift
Marumaru/CoreDataHandler.swift
Marumaru/Episode.swift
Marumaru/EpisodePopoverViewController.swift
Marumaru/MangaCollectionCell.swift
Marumaru/MangaEpisodeCell.swift
Marumaru/MangaEpisodePopoverCell.swift
Marumaru/MangaEpisodeViewController.swift
Marumaru/MangaHistoryViewController.swift
Marumaru/MangaSceneCell.swift
Marumaru/NetworkHandelr.swift
Marumaru/ResultMangaCell.swift
Marumaru/SceneDelegate.swift
Marumaru/SearchViewController.swift
Marumaru/TopRankMangaCell.swift
Marumaru/ViewController.swift
Marumaru/ViewGlobalExtension.swift
Marumaru/ViewMangaViewController.swift
Marumaru/WatchHistory+CoreDataProperties.swift

<Changes>
- 코드를 code convention에 맞게 정리 하였습니다.

CODE CONVENTION

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Base.lproj/Main.storyboard
Marumaru/HistoryHandler.swift
Marumaru/ImageCache.swift
Marumaru/ImageCacheHandler.swift
Marumaru/MangaEpisodeViewController.swift
Marumaru/MangaHistoryViewController.swift
Marumaru/NetworkHandelr.swift
Marumaru/SearchViewController.swift
Marumaru/ViewController.swift
Marumaru/ViewGlobalExtension.swift
Marumaru/ViewMangaViewController.swift

<New>
- Image Caching (realm & rxSwift)
- RealmSwift pod Added
- RxSwift/RxCocoa pod Added
<Fixed>
- dark background cell on Dark Appearance fixed to bright background color cell (SeachVC, EpisodeVC)
- status bar icon color fixed to static black color

Image Caching 📀

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/MangaEpisodeViewController.swift
Marumaru/MangaHistoryViewController.swift
Marumaru/SafeAreaInset.swift
Marumaru/SearchViewController.swift
Marumaru/ViewController.swift
Marumaru/ViewGlobalExtension.swift

<New>
- scale clear history button on MangaHistoryVC
- episode size label translate animation on MangaEpisodeVC
<Fixed>
- mainView view calculating delay fixed

Transition Animation modification 🌱

---

Marumaru/Base.lproj/Main.storyboard
Marumaru/GlobalExtension.swift
Marumaru/MangaThumbnailCollectionCell.swift
Marumaru/ViewMangaViewController.swift

<New>
- Double Tap to Zoom In & Out

Double Tap to Zoom In & Out 🔍

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Base.lproj/Main.storyboard
Marumaru/ColorSet.swift
Marumaru/GlobalExtension.swift
Marumaru/ImageCacheHandler.swift
Marumaru/MangaEpisodeViewController.swift
Marumaru/NetworkHandelr.swift
Marumaru/SceneScrollView.swift
Marumaru/SceneScrollViewCell.swift
Marumaru/SearchViewController.swift
Marumaru/ViewController.swift
Marumaru/ViewMangaViewController.swift
Marumaru/WatchHistoryHandler.swift
Marumaru/WatchHistoryViewController.swift
Podfile

<Changes>
- Scene scrollview top & bottom insets added
- now realm write safely
<Fixed>
- Scene scrollview cell image sequential loading stabilized
- MemoryLeak issue fixed🚰

SceneScrollView renewal 🎉

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ImageCacheHandler.swift
Marumaru/SearchViewController.swift
Marumaru/UserDefaultsHandler.swift
Marumaru/ViewController.swift
Podfile.lock

<New>
- Clear image cache data once every three days

ImageCache

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Array+IsInBound.swift
Marumaru/ComicDetail.storyboard
Marumaru/ComicDetailViewController.swift
Marumaru/ComicEpisodeThumbnailTableCell.xib
Marumaru/ComicStripViewController.swift
Marumaru/ComicStripViewModel.swift
Marumaru/ComicThumbnailCollectionCell.xib
Marumaru/Localizable.strings
Marumaru/MainViewController.swift
Marumaru/MainViewModel.swift
Marumaru/SearchComicViewController.swift
Marumaru/SearchResultComicCollectionCell.xib
Marumaru/String+Localizable.swift
Marumaru/ThumbnailView.swift
Marumaru/WatchHistoryViewController.swift
Marumaru/WatchHistoryViewModel.swift
R.generated.swift

- Fix episode indexing
- Sort watch histories by date
- Add comic detail thumbnail image failure state
- Fix SearchResultCollectionView content insets
- Fix involving white space to search keyword
- Add fade animation to setThumbnailShadow
Ref: #48

Feat: Add localizable string

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ComicDetailViewController.swift
Marumaru/ComicDetailViewModel.swift
Marumaru/ComicEpisodeThumbnailTableCell.swift
Marumaru/ComicEpisodeThumbnailTableCell.xib
Marumaru/ComicStripViewController.swift
Marumaru/ComicStripViewModel.swift
Marumaru/LottieAnimationView.swift
Marumaru/MarumaruApiService.swift
Marumaru/MarumaruApiServiceViewModel.swift
Marumaru/WatchHistoryViewModel.swift

- Add recent watching indicator to comic episode cell
Ref: #47

Fix: Fix watched episode state on ComicDetailVC

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ComicDetailViewController.swift
Marumaru/ComicInfo.swift
Marumaru/DescriptionHeaderReusableView.swift
Marumaru/DescriptionHeaderReusableView.xib
Marumaru/Localizable.strings
Marumaru/SearchComicViewController.swift
Marumaru/SearchHistory.swift
Marumaru/SearchHistoryManager.swift
Marumaru/SearchHistorySection.swift
Marumaru/SearchHistoryViewController.swift
Marumaru/SearchHistoryViewModel.swift
Marumaru/SearchResultSection.swift
Marumaru/SearchResultViewController.swift
Marumaru/SearchResultViewModel.swift
Marumaru/SingleButtonFooterReusableView.swift
Marumaru/SingleButtonFooterReusableView.xib
Marumaru/WatchHistoryViewController.swift
R.generated.swift

- Add description header to SearchHistoryCollectionView
- Add delete all footer button to SearchHistoryCollectionView
- Add description header to SearchRestulViewCollectionView
- Optimize switching child ViewControllers of SearchComicViewController
Ref: #60

Feat: Add header and footer view to SearchHistory & SearchResult

---

Marumaru/ComicDetailViewController.swift
Marumaru/UIView+Animation.swift

- Fix scroll to bottom button fade in & out animation issue

Fix: Fix fade in & out animation

---

Marumaru/ComicDetailViewController.swift
Marumaru/ComicDetailViewModel.swift
Marumaru/ComicStripViewController.swift
Marumaru/ComicStripViewModel.swift

- Add auto scroll to recent watching episode row

Fix: Fix recent watching episode update issue

---

Marumaru/ComicStrip.storyboard

- Change episode title truncate tail to middle in ComicStripViewController

Fix: Change episode title truncate tail to middle

---

Marumaru/ComicDetailViewController.swift
Marumaru/ComicEpisodeThumbnailTableCell.swift
Marumaru/ComicThumbnailCollectionCell.swift
Marumaru/ComicThumbnailCollectionCell.xib
Marumaru/MainViewController.swift
Marumaru/MainViewModel.swift
Marumaru/SearchResultComicCollectionCell.swift
Marumaru/SearchResultViewController.swift

- Cancel kingfisher image request on prepareToReuse State

Pref: Optimize reusable cells

---

Marumaru/ComicStripViewModel.swift
Marumaru/WatchHistory.swift
Marumaru/WatchHistoryManager.swift

Fix: Fix watch history date

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ComicStirpScrollView.swift
Marumaru/ComicStripScrollViewModel.swift

Fix: Fix update comic strip scroll view constraints

---

Marumaru/MarumaruApiService.swift

Fix: Limit document cache size for performance

---

Marumaru/ComicStripViewModel.swift
Marumaru/WatchHistoryManager.swift

- Fix issue that the updated thumbnail image was not recored to watch history

Fix: Fix watch history thumbnail image

---

Marumaru/ComicStripViewModel.swift
Marumaru/WatchHistoryManager.swift

HotFix: Fix watch history thumbnail image

---

Marumaru/BaseViewController.swift
Marumaru/SearchComic.storyboard
Marumaru/SearchHistory.storyboard
Marumaru/SearchHistoryViewController.swift
Marumaru/SearchResultViewController.swift

- Fix update search history collection view flowlayout
- Fix update search result collection view flowlayout
Ref: #89
close #89

Fix: Fix update collection view flowayouts

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/BaseViewController.swift
Marumaru/ComicStirpScrollView.swift
Marumaru/ComicStripViewController.swift

- Fix scrollToTop inset size in ComicStripViewController
Ref: #91
close #91

Fix: Remove hide and show status bar in ComicStripViewController

---

Marumaru/ComicStirpScrollView.swift
Marumaru/ComicStripScrollViewModel.swift

Fix: Scroll to the correct position when orientation did change

---

Marumaru/ComicDetailViewController.swift
Marumaru/MainViewController.swift
Marumaru/PopOverComicEpisodeViewController.swift
Marumaru/SearchHistoryViewController.swift
Marumaru/SearchResultViewController.swift
Marumaru/WatchHistoryViewController.swift

Style: Modularize registering nib from setup

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/CRUDable.swift
Marumaru/SearchHistoryManager.swift
Marumaru/WatchHistoryManager.swift

Style: Add 'CRUDable' protocol for reusability

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/BaseViewController.swift
Marumaru/Bookmark.storyboard
Marumaru/BookmarkViewController.swift
Marumaru/BookmarkViewModel.swift
Marumaru/ComicBookmark.swift
Marumaru/ComicBookmarkManager.swift
Marumaru/ComicDetail.storyboard
Marumaru/ComicDetailViewController.swift
Marumaru/ComicDetailViewModel.swift
Marumaru/ComicThumbnailCollectionCell.xib
Marumaru/Localizable.strings
Marumaru/MainTabBarController.swift
Marumaru/MainViewController.swift
Marumaru/SearchResultViewController.swift
Marumaru/WatchHistoryManager.swift
R.generated.swift

Feat: Add bookmark feature

---

Marumaru/ComicDetail.storyboard
Marumaru/ComicDetailViewController.swift
Marumaru/ComicDetailViewModel.swift
R.generated.swift

Feat: Add play first episode button

---

Marumaru/Bookmark.storyboard
R.generated.swift

Fix minimum pod deployment version

---

Marumaru/CategoryChipCollectionCell.xib
Marumaru/ComicCategory.storyboard
Marumaru/ComicCategoryViewController.swift

Fix: Stabilize category CollectionView

---

Marumaru/SceneDelegate.swift

Feat: Add secure blur view

---

Marumaru/BookmarkViewController.swift
Marumaru/CategoryChipCollectionCell.swift
Marumaru/CategoryChipCollectionCell.xib
Marumaru/ComicCategory.storyboard
Marumaru/ComicCategoryViewController.swift
Marumaru/ComicDetailViewController.swift
Marumaru/MainViewController.swift
Marumaru/SearchResultViewController.swift
Marumaru/WatchHistoryViewController.swift

- Change comic category chip size
Ref: #116 
close #116

Feat: Fix KingFisher image transition

---

Marumaru/ComicDetailViewController.swift
Marumaru/MarumaruApiService.swift

- Update base path "marumaru261" to "marumaru262"
Ref: #124
close #124

Fix: Fix episode amount label skeleton view

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ComicCategory.swift
Marumaru/ComicCategoryViewController.swift
Marumaru/ComicCategoryViewModel.swift
Marumaru/IndicatorButton.swift
Marumaru/MarumaruApiService.swift
Marumaru/ShowComicOptionFloatinPanelLayout.swift
Marumaru/ShowMoreReusableView.swift
Marumaru/ShowMoreReusableView.xib
R.generated.swift

Feat: Add category paging feature

---

Marumaru/BaseViewController.swift
Marumaru/ComicStirpScrollView.swift
Marumaru/ComicStrip.storyboard
Marumaru/ComicStripViewController.swift

- Change comic strip background color 'BackgroundWhite' to 'UIColor.white'
Ref: #128
close #128

Fix: Fix comic strip scrollview content insets

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/BookmarkViewController.swift
Marumaru/BookmarkViewModel.swift
Marumaru/ComicCategoryViewController.swift
Marumaru/ComicCategoryViewModel.swift
Marumaru/ComicDetailViewController.swift
Marumaru/ComicDetailViewModel.swift
Marumaru/ComicStirpScrollView.swift
Marumaru/ComicStripViewController.swift
Marumaru/ComicStripViewModel.swift
Marumaru/MainViewController.swift
Marumaru/MainViewModel.swift
Marumaru/MarumaruApiService.swift
Marumaru/PopOverComicEpisodeViewController.swift
Marumaru/PopOverComicEpisodeViewModel.swift
Marumaru/SearchHistoryViewController.swift
Marumaru/SearchHistoryViewModel.swift
Marumaru/SearchResultViewController.swift
Marumaru/SearchResultViewModel.swift
Marumaru/ShowComicOptionAlertViewController.swift
Marumaru/ShowComicOptionAlertViewModel.swift

- Improve viewModel stability.
Remove raw item arrays and use BehaviorRelay.value
- Fix comic strip scrollview safe area insets
Ref: #133
close #133

Pref: Improve viewModel stability

---

Marumaru/ComicEpisodeThumbnailCollectionCell.swift
Marumaru/ComicThumbnailCollectionCell.swift

Fix: Show thumbnail image placeholder label on prepareForReuse

---

Marumaru/BaseViewController.swift
Marumaru/Main.storyboard
Marumaru/MainViewController.swift
Marumaru/MarumaruApiService.swift
Marumaru/SearchComic.storyboard
Marumaru/WatchHistory.storyboard
Marumaru/WatchHistoryViewController.swift

- AppBar base view changed from 'UIVisualEffectView' to 'UIView'
- Base path changed from '262' to '263'
Ref: #137 #138
close #137 #138

Design: Change appBar styles

---

Marumaru/MainViewController.swift

Feat: Disable refresh buttons on loading state

---

Marumaru/CategoryChipCollectionCell.swift
Marumaru/ComicCategoryViewController.swift
Marumaru/ComicDetail.storyboard
Marumaru/ComicStirpScrollView.swift
Marumaru/ComicThumbnailCollectionCell.swift
Marumaru/ComicThumbnailCollectionCell.xib
Marumaru/SceneDelegate.swift
Marumaru/WatchHistoryViewController.swift

- Remove comments
- Change comic category chip selected color 'AccentOrange'  to 'AccentIndigo'
- Fix comic category chip border color issue that border color is not changed when trait collection did change
- Remove secure view cover feature
- Hide update cycle view of ComicCollectionCell if update cycle is not classified
- Add watch history bottom inset (24px) on WatchHistoryViewController
Ref: #143
close #143

Design: Fix design issues

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ComicStripViewController.swift
Marumaru/MarumaruApiService.swift
Podfile
Podfile.lock

Add 'SafeAreaBrush' pod I made 🙃
Update base path from ''263 to '264'
Ref: #140
close #140

Design: Add visual effect status bar to ComicStripViewController

---

Marumaru/MainViewController.swift

- Fix main collection cells out of bounds to invisible when trait collection did change
Ref: #115
close #115

Fix: Fix main collection vissible issue

---

Marumaru/BookmarkViewController.swift
Marumaru/ComicBookmark.swift
Marumaru/ComicCategoryViewController.swift
Marumaru/ComicDetailViewController.swift
Marumaru/ComicEpisodeThumbnailCollectionCell.swift
Marumaru/ComicEpisodeThumbnailTableCell.swift
Marumaru/ComicRankTableCell.swift
Marumaru/ComicThumbnailCollectionCell.swift
Marumaru/MainViewController.swift
Marumaru/MarumaruApiService.swift
Marumaru/PopOverComicEpisodeTableCell.swift
Marumaru/PopOverComicEpisodeViewController.swift
Marumaru/SearchHistoryCollectionCell.swift
Marumaru/SearchHistoryViewController.swift
Marumaru/SearchResultComicCollectionCell.swift
Marumaru/SearchResultViewController.swift
Marumaru/WatchHistory.swift
Marumaru/WatchHistoryViewController.swift

Refactor: Configure cell datas in each cell

---

Marumaru/ComicDetailViewModel.swift

Feat: Block bookmark while loading comic detail datas

---

Marumaru/Base.lproj/LaunchScreen.storyboard
R.generated.swift

- Fix launch screen background color 'SystemBackgroundColor' to 'AccentDarkGray'
Ref: #161
close #161

Design: Fix launch screen background color

---

Marumaru/SplashViewController.swift

- Change SplashViewController status bar style 'system' to 'lightContent'
Ref: #163
close #163

Design: Change SplashViewController status bar style

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/ComicCategoryViewController.swift
Marumaru/ComicCategoryViewModel.swift
Marumaru/ComicDetailViewModel.swift
Marumaru/ComicEpisode.swift
Marumaru/ComicInfo.swift
Marumaru/ComicInfoSection.swift
Marumaru/ItemPlaceHoldable.swift
Marumaru/MainViewController.swift
Marumaru/MainViewModel.swift
Marumaru/SearchResultViewModel.swift
Marumaru/SectionPlaceHoldable.swift

-  Fix comic category section id to reload sections that only newly added
- Add 'ItemPlaceHoldable' protocol to make fake items.
- Add 'SectionPlaceHoldable' protocol to make fake sections
Ref: #166
close #166

Fix: Fix datasource section reload issue

---

Marumaru/ComicStripViewController.swift

- Keep render comic strip scene when entering viewDidAppear from viewDidDisappear
Ref: #168
close #168

Fix: Fix comic strip rendering issue

---

Marumaru/Sources/Controllers/SplashViewController.swift
Marumaru/Sources/Services/BasePathManager.swift
Marumaru/Sources/Services/MarumaruApiService.swift
Marumaru/Sources/ViewModels/SplashViewModel.swift

Fix: Fix basePath management Logic

---

Marumaru/Sources/Controllers/BaseViewController.swift
Marumaru/Sources/Controllers/ComicStripViewController.swift
Marumaru/Sources/Views/ComicStripScrollView/ComicStirpScrollView.swift
Marumaru/Sources/Views/ComicStripScrollView/ComicStripScrollViewModel.swift

Fix: Reload scene images when enter foreground from the background

---

Marumaru/Sources/Controllers/ComicDetailViewController.swift

Fix: Fix comic detail initial info issue

---

Marumaru.xcodeproj/project.pbxproj

- Change version name from 1.0.1 to 2.0.0
- Change build version from 3 to 4
Ref: #181
close #181

Rename: Change version name to 2.0.0

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Sources/Controllers/BaseViewController.swift
Marumaru/Sources/Controllers/BookmarkViewController.swift
Marumaru/Sources/Controllers/ComicCategoryViewController.swift
Marumaru/Sources/Controllers/ComicDetailViewController.swift
Marumaru/Sources/Controllers/ComicStripViewController.swift
Marumaru/Sources/Controllers/MainViewController.swift
Marumaru/Sources/Controllers/PopOverComicEpisodeViewController.swift
Marumaru/Sources/Controllers/SearchComicViewController.swift
Marumaru/Sources/Controllers/SearchHistoryViewController.swift
Marumaru/Sources/Controllers/SearchResultViewController.swift
Marumaru/Sources/Controllers/ShowComicOptionAlertViewController.swift
Marumaru/Sources/Controllers/SplashViewController.swift
Marumaru/Sources/Controllers/WatchHistoryViewController.swift

- Change properties and ui declare conventions
Ref: #185
close #185

Rename: Wrap RxDataSource types through typealias

---

Marumaru/Sources/Controllers/SplashViewController.swift
Marumaru/Sources/Services/BasePathManager.swift
Marumaru/Sources/SupportingFiles/basePath.rtf
Marumaru/Sources/ViewModels/SplashViewModel.swift

- Fix basePath updating scheduler from  Main to Background to make sure splash animation start at the start point
- Update basePath from '271' to '291'
Ref: #189
close: #189

Fix: Fix splash logic

---

Marumaru.xcodeproj/project.pbxproj

- Change build version name from '4' to '5'
Ref: #192
close: #192

Rename: Change version name from '2.0.0' to '2.0.1'

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Sources/Controllers/MainViewController.swift
Marumaru/Sources/Controllers/SearchComicViewController.swift
Marumaru/Sources/Controllers/WatchHistoryViewController.swift
Marumaru/Sources/Views/NavigationView.swift
Marumaru/Sources/Views/Storyboards/Bookmark.storyboard
Marumaru/Sources/Views/Storyboards/ComicCategory.storyboard
Marumaru/Sources/Views/Storyboards/Main.storyboard
Marumaru/Sources/Views/Storyboards/SearchComic.storyboard
Marumaru/Sources/Views/Storyboards/WatchHistory.storyboard

Design: Add custom navigationView scroll edge appearance

---

Marumaru/Sources/Controllers/ComicDetailViewController.swift
Marumaru/Sources/Controllers/SplashViewController.swift
Marumaru/Sources/Services/BasePathManager.swift
Marumaru/Sources/ViewModels/SplashViewModel.swift

Feat: Add maintaining server alert in SplashView

---

Marumaru/Sources/Controllers/BaseViewController.swift
Marumaru/Sources/Controllers/ComicStripViewController.swift
Marumaru/Sources/Controllers/SplashViewController.swift
Podfile
Podfile.lock

- Hide status bar in comic strip when appBar is hidden
- Remove 'SafeAreaBrush' pod

Feat: Hide status bar in comic strip

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Sources/Controllers/ComicStripViewController.swift
Marumaru/Sources/Services/BasePathManager.swift
Podfile.lock

<ComicStripViewController>
- Filter edge pan gesture recognizer 'recognized' state to prevent recognizer being called every time.
<BasePathManager>
- Update base path from 291 to 401
<CocoaPods>
- Update pods (latest version)

Fix: Fix edge pan gesture recognizer issue

---

Marumaru/Sources/Controllers/BaseViewController.swift
Marumaru/Sources/Controllers/ComicStripViewController.swift

<BaseViewController>
- Integrate navigation bar styles
<ComicStripViewController>
- Remove hide navigation bar to fix edge pan to pop ViewController

Fix: Fix edge pan gesture to dismiss issue

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Sources/Services/BasePathManager.swift
Marumaru/Sources/Services/MarumaruApiService.swift
Marumaru/Sources/Services/UserDefaultsManager.swift
Marumaru/Sources/Utils/UserDefault.swift

[Refactor] Refactor userDefaults management

---

Marumaru.xcodeproj/project.pbxproj
Marumaru/Sources/Services/DocumentProvider.swift
Marumaru/Sources/Services/MarumaruApiService.swift

Add DocumentProvider
Ref: #221

[Feat] Add document cache

---

Marumaru/Sources/Controllers/MainViewController.swift
Podfile
Podfile.lock

[Chore] Fix pod versions

---

Marumaru.xcodeproj/project.pbxproj

- Rename build number from 6 to 7

[Rename] Rename version name from 2.0.1 to 2.0.2

---

Marumaru.xcodeproj/project.pbxproj

- Update build version from 6 to 7

[Chore] Update version name from 2.0.2 to 2.1.0
